import type { MeetingScenarioId, MeetingScenarioProfile } from './types'

export const DEFAULT_SCENARIO_ID: MeetingScenarioId = 'general'

const sharedHintRules = [
  '口语化、克制、尊重他人',
  '强调“我们”“大家”，避免抢功或强势压人',
  '避免空泛框架词堆砌，给出可执行的推进动作',
]

const profiles: MeetingScenarioProfile[] = [
  {
    id: 'general',
    label: '通用会议',
    description: '适用于一般多人讨论、决策与协作会议',
    analystRole: '中文多人会议实时辅助分析器',
    domainHint: '多人讨论、决策、协作与信息同步场景',
    valueDimensions: ['会议目标', '参与对象', '事实与背景', '约束条件', '方案选项', '比较与取舍', '风险与兜底', '行动与负责人'],
    analystTone: '专业会议助理',
    phaseLabels: {
      'problem-framing': '问题澄清',
      'option-divergence': '方案发散',
      'alignment-building': '对齐取舍',
      'decision-lock': '决策收口',
    },
    phaseDefinitions: {
      'problem-framing': '正在澄清会议目标、事实背景、边界、约束或成功标准。',
      'option-divergence': '正在提出多个方案、方向或观点，尚未充分比较。',
      'alignment-building': '正在比较和整合方案、处理分歧并统一判断标准。',
      'decision-lock': '正在确认结论、行动项、负责人、时间或最终表述。',
    },
    phaseSignals: ['是否在统一目标与事实', '是否在提出多个选项', '是否在比较取舍或处理分歧', '是否在确认结论与行动'],
    participantPersona: '会议参与者',
    hintStyleRules: sharedHintRules,
    spokenSummaryLabel: '60 秒收尾发言',
    spokenSummaryLengthHint: '约 60 秒、160-260 字',
    summaryPurpose: '形成结论清晰、可直接口头复述的会议收尾发言',
    minutesFocus: ['议题与关键观点', '明确决策', '待定问题', '行动项、负责人和时间'],
    topicContextLabel: '会议主题背景',
    roleContextLabel: '参会角色',
    topicPlaceholder: '补充会议目标、背景、约束或希望解决的问题',
    rolePlaceholder: '补充你的角色、职责和关注点',
    quickQuestions: ['现在最需要推进什么？', '当前有哪些分歧？', '我下一句可以怎么说？'],
  },
  {
    id: 'group-interview',
    label: '群面 / 小组面试',
    description: '适用于无领导小组讨论和群体面试',
    analystRole: '中文群面实时辅助分析器',
    domainHint: '互联网、产品、HR、运营等结构化群体面试场景',
    valueDimensions: ['题目目标', '用户或对象', '核心痛点', '约束条件', '方案选项', '比较与取舍', '风险与兜底', '分工与落地', '汇报与总结'],
    analystTone: '高水平群面陪练',
    phaseLabels: {
      'problem-framing': '问题框定',
      'option-divergence': '方案发散',
      'alignment-building': '共识对齐',
      'decision-lock': '结论收束',
    },
    phaseDefinitions: {
      'problem-framing': '正在澄清题目、目标、用户、约束、评价标准或边界条件。',
      'option-divergence': '正在发散多个方案或方向，尚未明显比较取舍。',
      'alignment-building': '正在比较、取舍和整合方案，尝试形成共识。',
      'decision-lock': '正在敲定结论、汇报结构、分工或最终口径。',
    },
    phaseSignals: ['是否在统一题目理解、用户与目标', '是否在提出多个方案', '是否在比较、取舍、融合与说服', '是否在确定结论、汇报与分工'],
    participantPersona: '候选人',
    hintStyleRules: [...sharedHintRules, '体现真实群面实战感与团队协作意识'],
    spokenSummaryLabel: '120 秒总结汇报',
    spokenSummaryLengthHint: '约 120 秒、220-400 字',
    summaryPurpose: '生成适合群面结尾、能直接回答题目核心问题的团队总结汇报',
    minutesFocus: ['题目核心问题', '团队方案与取舍', '风险约束', '分工与落地'],
    topicContextLabel: '面试题背景',
    roleContextLabel: '候选人角色',
    topicPlaceholder: '粘贴面试题、目标、约束和补充材料',
    rolePlaceholder: '补充候选人角色、擅长方向和希望承担的职责',
    quickQuestions: ['当前群面最缺什么？', '我该如何化解分歧？', '给我一段可直接说的话'],
  },
  {
    id: 'design-review',
    label: '需求与方案评审',
    description: '适用于需求、产品、技术与设计方案评审',
    analystRole: '中文方案评审实时辅助分析器',
    domainHint: '跨职能需求澄清、方案评审与决策场景',
    valueDimensions: ['背景与目标', '用户价值', '需求范围', '方案与改动点', '成本与可行性', '风险与依赖', '取舍与决策', '验收与行动'],
    analystTone: '严谨的评审主持人',
    phaseLabels: {
      'problem-framing': '背景与目标澄清',
      'option-divergence': '方案与改动点铺开',
      'alignment-building': '争议与取舍',
      'decision-lock': '结论与待办确认',
    },
    phaseDefinitions: {
      'problem-framing': '正在澄清背景、目标、范围、用户价值和验收标准。',
      'option-divergence': '正在展开候选方案、设计细节或改动影响。',
      'alignment-building': '正在处理争议、比较成本收益、风险和依赖。',
      'decision-lock': '正在确认通过项、修改项、责任人和后续时间。',
    },
    phaseSignals: ['目标与范围是否明确', '候选方案是否充分展开', '争议与依赖是否被处理', '结论和待办是否有负责人'],
    participantPersona: '评审参与者',
    hintStyleRules: [...sharedHintRules, '优先基于目标、证据、风险和可验证标准表达'],
    spokenSummaryLabel: '评审结论播报',
    spokenSummaryLengthHint: '约 60 秒、160-260 字',
    summaryPurpose: '清楚复述评审结论、核心取舍、风险与待办',
    minutesFocus: ['评审范围', '关键争议与取舍', '通过或修改决定', '负责人、截止时间和验收标准'],
    topicContextLabel: '评审背景',
    roleContextLabel: '评审角色',
    topicPlaceholder: '补充需求背景、目标、方案链接摘要和约束',
    rolePlaceholder: '补充你在评审中的职责和重点关注项',
    quickQuestions: ['评审还缺哪些证据？', '当前核心取舍是什么？', '如何推动评审收口？'],
  },
  {
    id: 'brainstorm',
    label: '头脑风暴',
    description: '适用于创意发散、聚类与优选',
    analystRole: '中文头脑风暴实时辅助分析器',
    domainHint: '多人创意生成、聚类、筛选与方案孵化场景',
    valueDimensions: ['命题与目标', '目标对象', '创意方向', '差异化价值', '可行性', '组合机会', '筛选标准', '优选方案'],
    analystTone: '开放而有收敛能力的创意引导师',
    phaseLabels: {
      'problem-framing': '命题澄清',
      'option-divergence': '创意发散',
      'alignment-building': '归类聚合',
      'decision-lock': '优选定案',
    },
    phaseDefinitions: {
      'problem-framing': '正在澄清命题、目标对象、边界和创意标准。',
      'option-divergence': '正在大量提出创意，鼓励差异与联想。',
      'alignment-building': '正在聚类、组合、补强创意并形成方向。',
      'decision-lock': '正在按标准筛选优先创意并确定下一步验证。',
    },
    phaseSignals: ['命题边界是否清楚', '是否仍在鼓励新创意', '是否开始归类组合', '是否按标准优选并安排验证'],
    participantPersona: '头脑风暴参与者',
    hintStyleRules: [...sharedHintRules, '发散期避免过早否定，收敛期明确筛选标准'],
    spokenSummaryLabel: '创意成果总结',
    spokenSummaryLengthHint: '约 60 秒、160-260 字',
    summaryPurpose: '概括创意版图、优选方向、筛选理由与验证动作',
    minutesFocus: ['创意主题与分类', '代表性创意', '筛选标准与优选结果', '后续验证'],
    topicContextLabel: '创意命题背景',
    roleContextLabel: '参与角色',
    topicPlaceholder: '补充创意命题、目标对象、边界和筛选标准',
    rolePlaceholder: '补充你的专业背景和希望贡献的视角',
    quickQuestions: ['还有哪些不同方向？', '如何归类现有创意？', '哪些创意值得优先验证？'],
  },
  {
    id: 'team-sync',
    label: '团队同步 / 站会',
    description: '适用于进展同步、阻塞处理与行动确认',
    analystRole: '中文团队同步实时辅助分析器',
    domainHint: '项目进展同步、站会、阻塞协调与行动跟踪场景',
    valueDimensions: ['目标与里程碑', '已完成进展', '当前工作', '阻塞与风险', '依赖关系', '优先级变化', '负责人', '下一步与时间'],
    analystTone: '简洁务实的团队协调者',
    phaseLabels: {
      'problem-framing': '进展同步',
      'option-divergence': '问题暴露',
      'alignment-building': '阻塞对齐',
      'decision-lock': '行动确认',
    },
    phaseDefinitions: {
      'problem-framing': '正在同步目标、进展、当前状态和计划。',
      'option-divergence': '正在暴露问题、风险、变化和未决事项。',
      'alignment-building': '正在协调阻塞、依赖、优先级和资源。',
      'decision-lock': '正在确认行动项、负责人、截止时间与跟进方式。',
    },
    phaseSignals: ['进展与目标是否对齐', '问题和风险是否充分暴露', '阻塞与依赖是否完成协调', '行动是否明确到人和时间'],
    participantPersona: '团队成员',
    hintStyleRules: [...sharedHintRules, '表达保持简短，明确事实、阻塞和所需支持'],
    spokenSummaryLabel: '同步会收尾',
    spokenSummaryLengthHint: '约 45-60 秒、120-220 字',
    summaryPurpose: '快速总结进展、阻塞、决定和下一步行动',
    minutesFocus: ['进展与里程碑', '阻塞和风险', '依赖与决定', '行动项、负责人和截止时间'],
    topicContextLabel: '项目与同步背景',
    roleContextLabel: '团队角色',
    topicPlaceholder: '补充项目目标、里程碑和本次同步范围',
    rolePlaceholder: '补充你的团队角色、负责模块和依赖方',
    quickQuestions: ['当前最大阻塞是什么？', '哪些依赖还没对齐？', '下一步行动如何明确？'],
  },
]

export const SCENARIO_PROFILES = Object.fromEntries(
  profiles.map((profile) => [profile.id, profile]),
) as Record<MeetingScenarioId, MeetingScenarioProfile>
